# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.buildAdjacencyMatrix <- function(strings, cutoff, metric, method, drop_deg_one) {
    .Call(`_RPatternJoin_buildAdjacencyMatrix`, strings, cutoff, metric, method, drop_deg_one)
}

